### ISSUE TITLE
https://den.ooo/updater says 404

### ISSUE THREAD

**Issue by lucsoft** [boywithkeyboard/updater#36]

**Comment by boywithkeyboard** [comment]
@lucsoft sorry for the inconvenience, you should import it from `https://den.ooo/updater/mod.ts` instead. I'll update the documentation asap.

**Comment by boywithkeyboard** [comment]
The readme contains a clear warning that **this library is not stable** and I completely forgot about this project tbh.

**Comment by boywithkeyboard** [comment]
The readme contains a clear warning that **this library is not stable**.
