### ISSUE TITLE
Broken PRs with v0.18.0 

### ISSUE THREAD

**Issue by dkolba** [boywithkeyboard/updater#48]
Since v0.18.0 I get the following PR via `deno run -Ar --import-map=https://deno.land/x/update/deno.json https://deno.land/x/update/mod.ts -c ./deno.json`:

![Screenshot 2024-03-18 at 17 30 44](https://github.com/boywithkeyboard/updater/assets/335483/7f25c152-b90a-4dac-a5bc-ec2dded06414)

Dotenv auto-loading is documented here: https://deno.land/std@0.220.1/dotenv/mod.ts?s=load

**Comment by boywithkeyboard** [comment]
@dkolba Okay, my first guess is that has something to to with the support of *side effect imports* (as mentioned in the [release notes](https://github.com/boywithkeyboard/updater/releases/tag/v0.18.0)).

I'll release a fix asap.

Please also note that the [CLI won't receive new features](https://github.com/boywithkeyboard/updater/blob/main/docs/alternative_uses.md).

**Comment by boywithkeyboard** [comment]
@dkolba you also specified the args in the wrong order. It should instead be `deno run -Ar --import-map=https://deno.land/x/update/deno.json https://deno.land/x/update/mod.ts ./deno.json -c`.

You basically passed the option `-c` with the value `./deno.json` to the CLI, which is invalid.

**Comment by dkolba** [comment]
> @dkolba you also specified the args in the wrong order. It should instead be `deno run -Ar --import-map=https://deno.land/x/update/deno.json https://deno.land/x/update/mod.ts ./deno.json -c`.
> 
> You basically passed the option `-c` with the value `./deno.json` to the CLI, which is invalid.

That did the trick, thanks a bunch 🍕

**Comment by dkolba** [comment]
BTW - I'd appreciate if you'd reconsider keeping CLI support - Actions are GitHub only and right now the CLI also works with GitLab based projects...

**Comment by boywithkeyboard** [comment]
@dkolba, you didn't even leave a star 🥲. Aaanyway... I want to clean up the codebase and expand the project with more action-specific features.

Not sure about keeping it the way it is.

**Comment by boywithkeyboard** [comment]
The issue is still present.

**Comment by dkolba** [comment]
The weird thing now is, I always get an error about `deno check`, but it does not say what was checked or why it failed. 🤷‍♂️

> [!CAUTION]\
> `deno check` failed on some `.ts` files.

- **esm.sh**

  - [preact](https://github.com/preactjs/preact) × `10.19.6` → `10.19.7`

**Comment by boywithkeyboard** [comment]
@dkolba Try creating a task with the value `deno check **/*.ts` and run it. Depending on if you codebase has `.ts` files, `.mjs` files or `.js`, please change that value to the extension and run it again. Please open a separate issue if you want to request a new feature or a change.

Or if you want to simply chat, join [den.ooo's Discord server](https://den.ooo/discord) to contact me.

**Comment by dkolba** [comment]
Hmm, I already have a task check with `deno check main.ts dev.ts sparkle.ts`. Globbing with **/*.ts will never work in my project, because there are also file which need to be ignored.

Maybe make the typecheck configurable?

**Comment by boywithkeyboard** [comment]
@dkolba please read my previous message.

> Please open a separate issue if you want to request a new feature or a change.
